# Data Hyperparameters
D_SEQLEN: [240] #[90,120,180,240]
D_MASKRATIO: [0.5,0.4,0.6]

# Model Hyperparameters
M_NLAYERS: [4]
M_NHIDDEN: [72]
M_NHIDDENFF: [144]
M_NHEAD: [4]
M_FEATURENUM: [3]

# Train Hyperparameters
T_NUMEPOCHS: [15]
T_LR: [0.001]
T_BATCHSIZE: [64,96,32]
